# Importing Libraries Used

In [282]:
import pandas as pd

# Reading in Anime.csv

In [283]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('/Users/jossfranco/Downloads/PersonalProjects/DataAnalyst/Datasets/Anime.csv')
df.head()

,anime_id,Name,Score,Genres,English name,Japanese name,sypnopsis,Type,Episodes,Aired,Premiered,Producers,Licensors,Studios,Source,Duration,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,"In the year 2071, humanity has colonized sever...",TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,Bandai Visual,"Funimation, Bandai Entertainment",Sunrise,Original,24 min. per ep.,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,"other day, another bounty—such is the life of ...",Movie,1,"Sep 1, 2001",Unknown,"Sunrise, Bandai Visual",Sony Pictures Entertainment,Bones,Original,1 hr. 55 min.,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,"Vash the Stampede is the man with a $$60,000,0...",TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,Victor Entertainment,"Funimation, Geneon Entertainment USA",Madhouse,Manga,24 min. per ep.,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),ches are individuals with special powers like ...,TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,"TV Tokyo, Bandai Visual, Dentsu, Victor Entert...","Funimation, Bandai Entertainment",Sunrise,Original,25 min. per ep.,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,It is the dark century and the people are suff...,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,"TV Tokyo, Dentsu",Unknown,Toei Animation,Manga,23 min. per ep.,PG - Children,3710.0,4369,13224,18,642,7314,766,1108

# Data Understanding
- What is the `shape` of the Dataframe

- What `dtypes` are in the Data

In [284]:
df.shape

(14952, 25)

In [285]:
df.dtypes

anime_id           int64
Name              object
Score            float64
Genres            object
English name      object
Japanese name     object
sypnopsis         object
Type              object
Episodes          object
Aired             object
Premiered         object
Producers         object
Licensors         object
Studios           object
Source            object
Duration          object
Rating            object
Ranked           float64
Popularity         int64
Members            int64
Favorites          int64
Watching           int64
Completed          int64
On-Hold            int64
Dropped            int64
dtype: object

# Data Cleaning

- `drop` columns that will not be useful

- Checking and Dropping any NaN values `isna`

- Checking and Dropping any `duplicated` values

- Fix and Fill in columns that have data in them with the value "Unknown"
    - Turn the "Premiered" column into two new columns that repreesent the year and season the show aired
    - `drop` the "Premiered" column after extracting data needed

- Trim the "Genres" and "Rating" columns to only their main values 

- `drop` rows that had "Unknown" values after cleaning

- Turn "Year_Premiered", "Episodes", and "Ranked" columns to type int `astype(int)` after all of the "Unknown" columns were dropped

### Dropping unused columns

In [286]:
df.drop(columns={'anime_id', 'English name', 'Japanese name', 'sypnopsis', 'Producers', 'Licensors', 'Studios', 'Source', 'Duration'}, inplace=True)
df.head()

,Name,Score,Genres,Type,Episodes,Aired,Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
0,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678
1,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,"Sep 1, 2001",Unknown,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770
2,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925
3,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378
4,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,PG - Children,3710.0,4369,13224,18,642,7314,766,1108

### Checking to see if there are any NaN values in the table

In [287]:
df.isna().sum()

Name             0
Score            0
Genres           0
Type             0
Episodes         0
Aired            0
Premiered        0
Rating           0
Ranked        1721
Popularity       0
Members          0
Favorites        0
Watching         0
Completed        0
On-Hold          0
Dropped          0
dtype: int64

### Querying the table to look at the rows with NaN

In [288]:
results = df.query('Ranked.isna()')
results.head(10)

,Name,Score,Genres,Type,Episodes,Aired,Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
165,Gosenzo San'e,6.11,"Comedy, Hentai, Mystery, Supernatural",OVA,4,"Sep 25, 1998 to Mar 25, 1999",Unknown,Rx - Hentai,NaN,8469,2308,4,148,1072,100,122
180,Words Worth,6.75,"Adventure, Hentai, Demons, Magic, Fantasy",OVA,5,"Aug 25, 1999 to Nov 25, 2000",Unknown,Rx - Hentai,NaN,5518,7447,38,391,4406,264,265
188,Pure Mail,6.26,Hentai,OVA,2,"Sep 25, 2001 to Dec 21, 2001",Unknown,Rx - Hentai,NaN,7731,3114,14,177,1834,112,122
190,Pia Carrot e Youkoso!!,6.02,"Comedy, Romance, Hentai",OVA,3,"Oct 24, 1997 to Apr 24, 1998",Unknown,Rx - Hentai,NaN,7767,3074,5,156,1715,106,139
191,Pia Carrot e Youkoso!! 2,6.15,"Comedy, Romance, Hentai",OVA,3,"Oct 23, 1998 to Apr 23, 1999",Unknown,Rx - Hentai,NaN,8715,2097,4,99,1247,65,100
194,Shin Angel,6.28,"Comedy, Drama, Hentai, Romance",OVA,5,"Oct 21, 1994 to Nov 22, 1995",Unknown,Rx - Hentai,NaN,8362,2432,13,192,1125,105,141
197,Kuro no Danshou,5.76,"Hentai, Horror",OVA,4,"Oct 29, 1999 to Sep 25, 2000",Unknown,Rx - Hentai,NaN,8552,2254,7,123,1163,101,119
198,Mezzo Forte,6.65,"Action, Comedy, Hentai, Sci-Fi",OVA,2,"May 25, 2000 to Jun 25, 2001",Unknown,Rx - Hentai,NaN,3299,24730,93,753,16749,358,324
292,Nageki no Kenkou Yuuryouji,6.19,"Comedy, Hentai, Yuri",OVA,3,"Aug 5, 1994 to Oct 13, 1995",Unknown,Rx - Hentai,NaN,6737,4520,21,269,2475,169,175
296,A Kite,6.56,"Action, Hentai, Police, Drama",OVA,2,"Feb 25, 1998 to Oct 25, 1998",Unknown,Rx - Hentai,NaN,2294,48597,214,1219,33238,568,617

### Dropping all NaN values from the table

In [289]:
# dropping rows specifically from the 'Ranked' column since it is the only one with missing values
df.dropna(subset=['Ranked'], inplace=True)
# resetting the index so it is still in order after dropping values 
df.reset_index(inplace=True, drop=True)
df.isna().sum()

Name          0
Score         0
Genres        0
Type          0
Episodes      0
Aired         0
Premiered     0
Rating        0
Ranked        0
Popularity    0
Members       0
Favorites     0
Watching      0
Completed     0
On-Hold       0
Dropped       0
dtype: int64

### Checking to see if the number of expected rows dropped equals how many were actually dropped

In [290]:
df.shape # Number of rows before dropped (14952) - Number of rows that had NaN that were actually dropped (1721)

(13231, 16)

### Checking to see if there are any duplicated values in the table

In [291]:
df.duplicated().sum() # there were none in this set

0

### There are cells in this data that have the value "Unknown" in them which acts as NaN. I am checking how many are in each column

In [292]:
df.map(lambda x: "Unknown" in str(x)).sum()

Name             1
Score            0
Genres          42
Type             0
Episodes       135
Aired           25
Premiered     8810
Rating         335
Ranked           0
Popularity       0
Members          0
Favorites        0
Watching         0
Completed        0
On-Hold          0
Dropped          0
dtype: int64

### The "Premiered" column has a lot of missing values but can be fixed. 
-  PLAN:
    - Extract the Month and Year from the "Aired" column
    - Convert the Month into a season
    - Create two new columns with the season and year the anime premiered
    - Drop existing "Premiered" column

In [293]:
results = df.query('Premiered.str.contains("Unknown")')
results.head()

,Name,Score,Genres,Type,Episodes,Aired,Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
1,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,"Sep 1, 2001",Unknown,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770
21,Neon Genesis Evangelion: Death & Rebirth,7.45,"Drama, Mecha, Psychological, Sci-Fi",Movie,1,"Mar 15, 1997",Unknown,R - 17+ (violence & profanity),1742.0,833,180681,588,1941,146202,1069,961
22,Neon Genesis Evangelion: The End of Evangelion,8.51,"Sci-Fi, Dementia, Psychological, Drama, Mecha",Movie,1,"Jul 19, 1997",Unknown,R+ - Mild Nudity,102.0,195,572080,17811,8055,482918,2462,1499
24,Koukaku Kidoutai,8.29,"Action, Mecha, Police, Psychological, Sci-Fi, ...",Movie,1,"Nov 18, 1995",Unknown,R+ - Mild Nudity,236.0,265,468279,10362,8152,325682,3404,1927
25,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.73,"Action, Historical, Drama, Romance, Martial Ar...",OVA,4,"Feb 20, 1999 to Sep 22, 1999",Unknown,R - 17+ (violence & profanity),37.0,637,228484,6111,6359,150183,3124,1836

### Extracting the Month from the "Aired" column

In [294]:
aired_month = df['Aired'].str.slice(0,3)
aired_month.head()

0    Apr
1    Sep
2    Apr
3    Jul
4    Sep
Name: Aired, dtype: object

### Extracting the Year from the "Aired" column

In [295]:
aired_year = df['Aired'].str.split(',').str[1].str.slice(0,5)
aired_year.head()

0     1998
1     2001
2     1998
3     2002
4     2004
Name: Aired, dtype: object

### Helper method to convert the extracted months into the correct anime seasons

In [296]:
def seasons(month): 

   if(month == ('Jan')):  
    return 'Winter'
   elif(month == ('Feb')):
    return 'Winter'
   elif(month == ('Mar')):
    return 'Winter'
   elif(month == ('Apr')):
    return 'Spring'
   elif(month == ('May')):
    return 'Spring'
   elif(month == ('Jun')):
    return 'Spring'
   elif(month == ('Jul')):
    return 'Summer'
   elif(month == ('Aug')):
    return 'Summer'
   elif(month == ('Sep')):
    return 'Summer'
   elif(month == ('Oct')):
    return 'Fall'
   elif(month == ('Nov')):
    return 'Fall'
   elif(month == ('Dec')):
    return 'Fall'
   else: 
    return 'Unknown'

### Converting the months into the correct anime seasons

In [297]:
aired_season = aired_month.apply(seasons)
aired_season.head()

0    Spring
1    Summer
2    Spring
3    Summer
4    Summer
Name: Aired, dtype: object

### Creating the two new "Season_Premiered" and "Year_Premiered" columns and Dropping the existing "Premiered" column

In [298]:
df.drop(columns={'Aired', 'Premiered'}, inplace=True)
df.insert(5, "Season_Premiered", aired_season)
df.insert(6, "Year_Premiered", aired_year)
df.head()

,Name,Score,Genres,Type,Episodes,Season_Premiered,Year_Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
0,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,Spring,1998,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678
1,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,Summer,2001,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770
2,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,Spring,1998,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925
3,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,Summer,2002,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378
4,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,Summer,2004,PG - Children,3710.0,4369,13224,18,642,7314,766,1108

### Filling in NaN values in the "Year_Premiered" column with "Unknown" so they can be easily dropped later

In [299]:
df['Year_Premiered'] = df['Year_Premiered'].fillna("Unknown")

### After the cleaning of the "Premiered" column there are a lot less "Unknown" values

In [300]:
df.map(lambda x: "Unknown" in str(x)).sum()

Name                  1
Score                 0
Genres               42
Type                  0
Episodes            135
Season_Premiered    755
Year_Premiered      748
Rating              335
Ranked                0
Popularity            0
Members               0
Favorites             0
Watching              0
Completed             0
On-Hold               0
Dropped               0
dtype: int64

### Checking to make sure that no rows were lost during the cleaning and that only values were replaced

In [301]:
df.shape

(13231, 16)

### The "Genres" column has too many genres and will be trimmed to only the main genre

#### Before trim

In [302]:
df.head()

,Name,Score,Genres,Type,Episodes,Season_Premiered,Year_Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
0,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,Spring,1998,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678
1,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,Summer,2001,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770
2,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,Spring,1998,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925
3,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,Summer,2002,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378
4,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,Summer,2004,PG - Children,3710.0,4369,13224,18,642,7314,766,1108

#### After trim

In [303]:
genre = df['Genres'].str.split(',').str[0]
df.drop(columns='Genres', inplace=True)
df.insert(2, "Genre", genre)
df.head()

,Name,Score,Genre,Type,Episodes,Season_Premiered,Year_Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
0,Cowboy Bebop,8.78,Action,TV,26,Spring,1998,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678
1,Cowboy Bebop: Tengoku no Tobira,8.39,Action,Movie,1,Summer,2001,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770
2,Trigun,8.24,Action,TV,26,Spring,1998,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925
3,Witch Hunter Robin,7.27,Action,TV,26,Summer,2002,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378
4,Bouken Ou Beet,6.98,Adventure,TV,52,Summer,2004,PG - Children,3710.0,4369,13224,18,642,7314,766,1108

### The "Rating" column can be trimmed to only the rating itself without the description

#### Before trim

In [304]:
df.head()

,Name,Score,Genre,Type,Episodes,Season_Premiered,Year_Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
0,Cowboy Bebop,8.78,Action,TV,26,Spring,1998,R - 17+ (violence & profanity),28.0,39,1251960,61971,105808,718161,71513,26678
1,Cowboy Bebop: Tengoku no Tobira,8.39,Action,Movie,1,Summer,2001,R - 17+ (violence & profanity),159.0,518,273145,1174,4143,208333,1935,770
2,Trigun,8.24,Action,TV,26,Spring,1998,PG-13 - Teens 13 or older,266.0,201,558913,12944,29113,343492,25465,13925
3,Witch Hunter Robin,7.27,Action,TV,26,Summer,2002,PG-13 - Teens 13 or older,2481.0,1467,94683,587,4300,46165,5121,5378
4,Bouken Ou Beet,6.98,Adventure,TV,52,Summer,2004,PG - Children,3710.0,4369,13224,18,642,7314,766,1108

#### After trim

In [305]:
rating = df['Rating'].str.split(' ').str[0]
df.drop(columns='Rating', inplace=True)
df.insert(7, "Rating", rating)
df.head(10)

,Name,Score,Genre,Type,Episodes,Season_Premiered,Year_Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
0,Cowboy Bebop,8.78,Action,TV,26,Spring,1998,R,28.0,39,1251960,61971,105808,718161,71513,26678
1,Cowboy Bebop: Tengoku no Tobira,8.39,Action,Movie,1,Summer,2001,R,159.0,518,273145,1174,4143,208333,1935,770
2,Trigun,8.24,Action,TV,26,Spring,1998,PG-13,266.0,201,558913,12944,29113,343492,25465,13925
3,Witch Hunter Robin,7.27,Action,TV,26,Summer,2002,PG-13,2481.0,1467,94683,587,4300,46165,5121,5378
4,Bouken Ou Beet,6.98,Adventure,TV,52,Summer,2004,PG,3710.0,4369,13224,18,642,7314,766,1108
5,Eyeshield 21,7.95,Action,TV,145,Spring,2005,PG-13,604.0,1003,148259,2066,13907,78349,14228,11573
6,Hachimitsu to Clover,8.06,Comedy,TV,24,Spring,2005,PG-13,468.0,687,214499,4101,11909,81145,11901,11026
7,Hungry Heart: Wild Striker,7.59,Slice of Life,TV,52,Summer,2002,PG-13,1317.0,3612,20470,231,817,13778,828,1168
8,Initial D Fourth Stage,8.15,Action,TV,24,Spring,2004,PG-13,360.0,1233,117929,979,6082,90967,3053,1356
9,Monster,8.76,Drama,TV,74,Spring,2004,R+,30.0,169,614100,29436,64648,214491,47488,23008

### Dropping the rows that still have "Unknown" values after the cleaning

In [306]:
df = df[(df != 'Unknown').all(axis=1)]
# resetting the index so it is still in order after dropping values 
df.reset_index(inplace=True, drop=True)

In [307]:
df.map(lambda x: "Unknown" in str(x)).sum()

Name                1
Score               0
Genre               0
Type                0
Episodes            0
Season_Premiered    0
Year_Premiered      0
Rating              0
Ranked              0
Popularity          0
Members             0
Favorites           0
Watching            0
Completed           0
On-Hold             0
Dropped             0
dtype: int64

### The one "Name" row that has "Unknown" in it is not empty. "Unknown" is apart of its title

In [308]:
df.query('Name.str.contains("Unknown")')

,Name,Score,Genre,Type,Episodes,Season_Premiered,Year_Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
11032,King of Prism: Shiny Seven Stars IV - Louis x ...,6.51,Music,Movie,1,Spring,2019,PG-13,15018.0,11735,585,0,25,100,11,46

### Converting "Year_Premiered", "Episodes", and "Ranked" columns to type int after all of the "Unknown" columns were dropped

In [309]:
df['Year_Premiered'] = df['Year_Premiered'].astype(int)
df['Episodes'] = df['Episodes'].astype(int)
df['Ranked'] = df['Ranked'].astype(int)

### Final amount of rows and columns in the table after cleaning

In [310]:
df.shape

(12027, 16)

### A look at the table after cleaning

In [311]:
df.head(20)

,Name,Score,Genre,Type,Episodes,Season_Premiered,Year_Premiered,Rating,Ranked,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped
0,Cowboy Bebop,8.78,Action,TV,26,Spring,1998,R,28,39,1251960,61971,105808,718161,71513,26678
1,Cowboy Bebop: Tengoku no Tobira,8.39,Action,Movie,1,Summer,2001,R,159,518,273145,1174,4143,208333,1935,770
2,Trigun,8.24,Action,TV,26,Spring,1998,PG-13,266,201,558913,12944,29113,343492,25465,13925
3,Witch Hunter Robin,7.27,Action,TV,26,Summer,2002,PG-13,2481,1467,94683,587,4300,46165,5121,5378
4,Bouken Ou Beet,6.98,Adventure,TV,52,Summer,2004,PG,3710,4369,13224,18,642,7314,766,1108
5,Eyeshield 21,7.95,Action,TV,145,Spring,2005,PG-13,604,1003,148259,2066,13907,78349,14228,11573
6,Hachimitsu to Clover,8.06,Comedy,TV,24,Spring,2005,PG-13,468,687,214499,4101,11909,81145,11901,11026
7,Hungry Heart: Wild Striker,7.59,Slice of Life,TV,52,Summer,2002,PG-13,1317,3612,20470,231,817,13778,828,1168
8,Initial D Fourth Stage,8.15,Action,TV,24,Spring,2004,PG-13,360,1233,117929,979,6082,90967,3053,1356
9,Monster,8.76,Drama,TV,74,Spring,2004,R+,30,169,614100,29436,64648,214491,47488,23008
10,Naruto,7.91,Action,TV,220,Fall,2002,PG-13,660,8,1830540,65586,137167,1462223,61734,99806
11,Tennis no Ouji-sama,7.90,Action,TV,178,Fall,2001,PG-13,675,1039,141832,3124,11235,76881,12905,12516
12,Ring ni Kakero 1,6.38,Action,TV,12,Fall,2004,PG,6493,7333,3648,16,170,1333,145,296
13,School Rumble,7.94,Comedy,TV,26,Fall,2004,PG-13,625,514,275464,5137,12277,157789,12856,13491
14,Sunabouzu,7.42,Action,TV,24,Fall,2004,R,1844,1284,111734,790,6273,53819,6255,7951
15,Texhnolyze,7.76,Action,TV,22,Spring,2003,R+,896,823,182599,3671,11335,47532,9815,8112
16,Trinity Blood,7.32,Action,TV,24,Spring,2005,R,2240,936,158343,1479,7794,87958,8940,9349
17,Yakitate!! Japan,7.95,Comedy,TV,69,Fall,2004,PG-13,609,1666,80183,887,5007,39992,5764,4633
18,Zipang,7.51,Action,TV,26,Fall,2004,PG-13,1565,3985,16652,152,857,6807,721,599
19,Neon Genesis Evangelion,8.32,Action,TV,26,Fall,1995,PG-13,208,54,1160651,71308,66549,815938,35566,20358

# Converting new table to a .csv

In [312]:
# df.to_csv('/Users/jossfranco/Downloads/PersonalProjects/DataAnalyst/Datasets/Clean_Anime.csv', sep=',', header=True, index=False)